### ISSUE TITLE
Security issues when upgrading to 3.0

### ISSUE THREAD

**Issue by ScottGuymer** [PrometheusClientNet/Prometheus.Client.MetricServer#13]
Trying to upgrade the usage of the library to 3.0 and running into some issues when starting the Metrics Server.

The only real change I can see is moving the HttpListener.start() call from the background thread into the foreground.

We have some "secure" configurations that are hardened in various ways and when we deploy the code to this configuration we initially run into access denied errors for starting the HttpListener and when we have got it running we end up with a blank metrics screen.

cc: @jaeilkema

**Comment by ScottGuymer** [comment]
I created a quick branch to try and see if reverting the change had any impact and ran into som failing tests.

#12

**Comment by phnx47** [comment]
@ScottGuymer This is actual?

**Comment by ScottGuymer** [comment]
Yes, there seems to be some impact of this change on some of our configurations but we haven't had a chance to devote the time to track down the issue.

**Comment by marekr** [comment]
@phnx47 Why was 3.0 switched to using HttpListener for netstandard 2.0? HttpListener is an absolute nightmare to use on Windows. Kestrel worked fine but only builds for netstandard 1.3 now :/

**Comment by phnx47** [comment]
@marekr What problem with HttpListener? Is problem only with Windows ?
@sanych-sun Can you check it in Windows?

**Comment by sanych-sun** [comment]
@phnx47 It works for me.

@marekr could you please provide more details which problem caused by HttpListerner?

**Comment by marekr** [comment]
@phnx47 on Windows. HttpListener uses WCF and requires use of commands to add listener urls to a global ACL to allow access (or else you get Access denied errors)

https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/configuring-http-and-https?redirectedfrom=MSDN

**Comment by ScottGuymer** [comment]
This seems to be in line with the issues we were finding installing into a hardened OS.

**Comment by sanych-sun** [comment]
@marekr Wow! I didn't know that. It's sounds a little strange for me, because HttpListener is low-level API and in my "world" there is no way to low-level library to use high-level API (like WCF). Somehow I was thought HttpListener is a wrapper over the http.sys.

But anyway, @ScottGuymer  and @marekr I can create an intermediate version of the library to remove HttpListener at all to check if it causes your issue. I'll let you know once it done.

Thanks

**Comment by marekr** [comment]
@sanych-sun Actually my terminology is wrong. HttpListener is a wrapper over http.sys but http.sys and WCF end up sharing alot of functionality for HTTP. One of them is the annoying ACL list for setting up listeners.

**Comment by jaeilkema** [comment]
@sanych-sun: If your test succeeds I would like to try it.

**Comment by sanych-sun** [comment]
@ScottGuymer and @marekr Can you please try to use the "Prometheus.Client.MetricServer.Kestrel" package from MyGet in your environment to ensure that Kestrel helps to resolve the ACL issue?

**Comment by sanych-sun** [comment]
@ScottGuymer , @marekr and @jaeilkema do you have environment to check the new package? We do need help from you to validate the changes.

**Comment by ScottGuymer** [comment]
Apologies for the radio silence. This isn't something we have been able to dedicate the time to be able to look at. 

I cant give a specific timescale when we will be able to look into it at the moment as it can take some time to setup the correct environment.

Although everything in this discussion fits almost exactly with the issues we were having and before the change to http listener things seemed to work fine in our environment. I have a lot of confidence this will solve the issue we were seeing.

**Comment by malachib** [comment]
Hitting this also.  Had to:

* do a `Host = "+"` in `MetricServerOptions`
* use `Everyone` for `netsh http` user.  My own logged in user ended up producing 503 error codes

**Comment by sanych-sun** [comment]
@malachib we are about to release version build on top of Kestrel and remove HttpListener implementation at all. It would be nice if you can test if it helps.

Could you please pull the latest package from MyGet and try it on your environment?

https://www.myget.org/feed/prometheus-client-net/package/nuget/Prometheus.Client.MetricServer

Thanks

**Comment by malachib** [comment]
Will do!

**Comment by sanych-sun** [comment]
@malachib Thank you so much! We will make the package available soon.

**Comment by sanych-sun** [comment]
3.1 version is now available.
